name: Daily Stock Data Fetch

on:
  schedule:
    # 每天UTC时间01:00运行（北京时间09:00）
    - cron: '0 1 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run fetch script
      env:
        TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
      run: |
        python fetch_kline.py --datasource mootdx --workers 5
        
    - name: Commit and push data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git diff --staged --quiet || git commit -m "Auto update stock data $(date '+%Y-%m-%d %H:%M:%S')"
        git push
